WebApplicationTest3/Controllers/PartyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationTest3.Controllers
{
    public class PartyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplicationTest3/Controllers/ProfileController.cs
using AutoMapper;
using FriendsTracker.Data.Entities;
using FriendsTracker.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebApplicationTest3.Data;

namespace FriendsTracker.Controllers
{

    public class ProfileController : Controller
    {

        IUserTrackingRepository _userTrackingRepository;
        private UserManager<ApplicationUser> _userManager { get; set; }
        private IMapper _mapper;

        public ProfileController(IUserTrackingRepository userTrackingRepository, UserManager<ApplicationUser> userManager, IMapper mapper)
        {
            _userTrackingRepository = userTrackingRepository;
            _userManager = userManager;
            _mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {

            // use automapper to change to UserProfileViewModel
            var result = await GetCurrentProfile();
            return View(result);
        }

        private async Task<UserProfileViewModel> GetCurrentProfile()
        {
            //get current profile
            var user = await _userManager.FindByNameAsync(this.User.Identity.Name);

            var profileModel = new UserProfileViewModel() { UserName = this.User.Identity.Name, AvatarType =  Shared.Avatar.child.ToString() };

            var profile = _userTrackingRepository.GetUserProfile(user.UserName);

            if (profile != null)
            {
                profileModel =  _mapper.Map<UserProfile, UserProfileViewModel>(profile);

                //profileModel.UserName = profile.ApplicationUserName;
                //profileModel.AvatarType = profile.AvatarType.ToString();
                //profileModel.Status = profile.Status;
                //profileModel.Gender = false;
                //profileModel.ImageUrl = profile.ImageUrl;
            }
            return profileModel;
        }

        public IActionResult Create()
        {
            //used to carete a new profile for a new user that accepted an invitation
            ViewData[""] = "In ProfileController";
            return View();
        }

        public IActionResult Update()
        {
            var result = GetCurrentProfile();
            return View(result.Result);
        }
        [HttpPost]
        public async Task<IActionResult> Update(UserProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByNameAsync(this.User.Identity.Name);

                    var currentProfile = _userTrackingRepository.GetUserProfile(user.UserName);

                    if (currentProfile == null)
                    {
                        currentProfile = _mapper.Map<UserProfileViewModel, UserProfile>(model);
                    }
                    else
                    {
                        currentProfile.Status = model.Status;
                        currentProfile.AvatarType = model.AvatarType;
                    }

                    if (model.ImageUpload != null && model.ImageUpload.FileName != null && model.ImageUpload.Length > 0)
                    {
                        //validate extension
                        var supportedTypes = new[] { "gif", "png", "jpeg" };
                        var fileExt = System.IO.Path.GetExtension(model.ImageUpload.FileName).Substring(1);
                        if (!supportedTypes.Contains(fileExt))
                        {
                            ViewData["Problem"] = "file upload type is not supported";
                            return View(model);
                        }

                        var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot/uploads",
                        model.ImageUpload.FileName);

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await model.ImageUpload.CopyToAsync(stream);
                        }

                        currentProfile.ImageUrl = "/uploads/" + model.ImageUpload.FileName;
                        model.ImageUrl = currentProfile.ImageUrl;
                    }

                   
                    _userTrackingRepository.UpdateUserProfile(currentProfile);
                    return RedirectToAction("Index");
                }
                catch(Exception exc)
                {
                    ViewData["Problem"] = $"exception ocured: {exc.Message}";
                }
                
            }
            else
            {
                //set some error message in form
                ViewData["Problem"] = "Invalid form  data";
            }

            //todo code to update profile
            
            //make sure its an image file and save
            return View(model);
        }
    }

}

WebApplicationTest3/Controllers/UserTrackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FriendsTracker.Data.Entities;
using FriendsTracker.ViewModels;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplicationTest3.Data;

namespace WebApplicationTest3.Controllers
{
    public class UserTrackingController : Controller
    {
        IUserTrackingRepository _userTrackingRepository;
        private UserManager<ApplicationUser> _userManager { get; set; }
        private IMapper _mapper;

        public UserTrackingController(IUserTrackingRepository userTrackingRepository, UserManager<ApplicationUser> userManager, IMapper mapper)
        {
            _userTrackingRepository = userTrackingRepository;
            _userManager = userManager;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            //show infromation about friends
            return View();
        }

        [Authorize]
        public async Task<IActionResult> All()
        {
            if (!this.User.Identity.IsAuthenticated)
                throw new NotImplementedException();
            //show list of the current user user trackings
            {
                var vmTrackings = new List<UserTrackingViewModel>();

                var user = await _userManager.FindByNameAsync(User.Identity.Name);

                var result = await _userManager.IsInRoleAsync(user, "Admin");
                if (result)
                {

                    return RedirectToAction("AllTrackers");
                }
                
                //get tracked users
                var trackedUsers = _userTrackingRepository.GetUserTrackings(user.UserName);
                
                if (trackedUsers != null && trackedUsers.Count() > 0)
                {
                    foreach(var tu in trackedUsers)
                    {
                        var vmTrackedUser = _mapper.Map<UserTrackingViewModel>(tu);
                        vmTrackings.Add(vmTrackedUser);
                    }
                    
                    return View(vmTrackings);
                }

                return View(vmTrackings);
            }
        }

        [Authorize]
        
        public async Task<IActionResult> AllTrackers()
        {
            //simple comment
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var result = await _userManager.IsInRoleAsync(user, "Admin");
            if (result)
            {
                ViewData["access"] = "admin";
            }

            var vmTrackers = new List<UserTrackerViewModel>();

            var trackers = _userTrackingRepository.GetTrackers();
            if (trackers != null && trackers.Count() > 0)
            {
                foreach (var t in trackers)
                {
                    var vmTracker = _mapper.Map<UserTrackerViewModel>(t);
                    vmTrackers.Add(vmTracker);
                }
            }
            return View(vmTrackers);
            
        }

        //API GET
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        [HttpGet]
        
        public IActionResult Trackers()
        {
            return Ok(_userTrackingRepository.GetTrackers());
        }

        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        [HttpGet]
        public IActionResult Trackings(string userName)
        {
            return Ok(_userTrackingRepository.GetUserTrackings(userName));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(InvitationViewModel model)
        {
            //review
            return RedirectToAction("AllTrackers");
        }
    }
}

WebApplicationTest3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hello</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
        @*<link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />*@
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        
    </environment>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">User Tracker</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a asp-controller="UserTracking" asp-action="All">User Tracking</a></li>
                <li><a asp-controller="Party" asp-action="Index">Parties</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Profile
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                            <li><a asp-controller="Profile" asp-action="Index">View Profile</a></li>
                        </ul>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-controller="Admin" asp-action="Index">Admin</a></li>
                    }
                }
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @*<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>*@
                @if (!User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Account" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                }
            </ul>

        </div>
    </nav>

    <div class="text-center lead">@ViewData["Title"]</div>
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/font-awesome/js/all.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>